businessAddress: |-
  Venetiehof 19
  1019NA Amsterdam

  Netherlands
socialMedia:
  - link: 'https://www.facebook.com/Statik-Web-Design-929561014098886/'
    name: Facebook
  - link: 'https://twitter.com/robertbrosma'
    name: Twitter
